[package]
name = "hexa"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hexa"
path = "src/main.rs"

[dependencies]
hexa-compiler = { path = "../compiler" }
hexa-crypto = { path = "../crypto" }
hexa-runtime = { path = "../runtime" }
toml = "0.8"
rpassword = "7"
zeroize = "1"
