//! x86-64 native code generation (AT&T assembly emission).
//!
//! The lowered IR is turned into a position-independent ELF-friendly `.s`
//! file containing user functions plus a libc-free runtime driven by raw
//! syscalls. The system assembler (`as`) and linker (`ld`) turn the output
//! into a native ELF executable. Nothing is transpiled: the user program is
//! genuine native machine code.

use crate::ir::{Function, Inst, Module};

const RUNTIME: &str = include_str!("runtime_x64.s");

/// Map a user function name to its emitted symbol.
pub fn fn_symbol(name: &str) -> String {
    if name == "main" {
        "hexa_main".to_string()
    } else {
        format!("hexa_fn_{}", name)
    }
}

/// Emit the full assembly source for a module.
pub fn emit(module: &Module, debug: bool) -> String {
    let mut o = String::new();
    o.push_str("# Generated by the HEXA compiler (x86-64 / System V).\n");
    o.push_str("# This is native machine code emitted by HEXA, not a transpilation.\n");
    o.push_str("\t.text\n");
    if debug {
        o.push_str("\t.globl hexa_release_version\n");
    }
    for f in &module.funcs {
        emit_fn(&mut o, f, debug);
    }
    // static data (string/bytes literals) collected during function emission
    emit_data_section(&mut o);
    o.push_str(RUNTIME);
    o
}

use std::sync::Mutex;
static DATA: Mutex<Vec<Vec<u8>>> = Mutex::new(Vec::new());

fn reset_data() {
    *DATA.lock().unwrap() = Vec::new();
}

fn record_data(bytes: Vec<u8>) -> usize {
    let mut g = DATA.lock().unwrap();
    g.push(bytes);
    g.len() - 1
}

fn emit_data_section(o: &mut String) {
    let g = DATA.lock().unwrap();
    if g.is_empty() {
        return;
    }
    o.push_str("\t.section .rodata\n");
    o.push_str("\t.align 8\n");
    for (i, bytes) in g.iter().enumerate() {
        o.push_str(&format!("Lstr{}:\n", i));
        o.push_str(&format!("\t.quad {}\n", bytes.len()));
        if !bytes.is_empty() {
            let line = bytes
                .iter()
                .map(|b| b.to_string())
                .collect::<Vec<_>>()
                .join(", ");
            o.push_str(&format!("\t.byte {}\n", line));
        }
    }
}

fn emit_fn(o: &mut String, f: &Function, debug: bool) {
    let sym = fn_symbol(&f.name);
    let nlocals = f.locals.len();
    let frame = ((nlocals * 8) + 15) & !15;
    o.push_str(&format!("\t.globl {}\n", sym));
    o.push_str(&format!("\t.type {}, @function\n", sym));
    if debug {
        o.push_str(&format!("\t// function {} params={} ret={:?} locals={}\n", f.name, f.params.len(), f.ret, nlocals));
    }
    o.push_str(&format!("{}:\n", sym));
    o.push_str("\tpushq %rbp\n");
    o.push_str("\tmovq %rsp, %rbp\n");
    if frame > 0 {
        o.push_str(&format!("\tsubq ${}, %rsp\n", frame));
    }
    // copy parameters into their slots (params occupy slots 0..n-1)
    let n = f.params.len();
    for i in 0..n {
        let off = 16 + 8 * (n - 1 - i);
        o.push_str(&format!("\tmovq {}(%rbp), %rax\n", off));
        o.push_str(&format!("\tmovq %rax, -{}(%rbp)\n", 8 * (i + 1)));
    }
    for (idx, inst) in f.body.iter().enumerate() {
        let lname = format!("L{}_{}", sym, idx);
        o.push_str(&format!("{}:\n", lname));
        emit_inst(o, inst, idx, &f);
    }
    o.push_str(&format!("Lret_{}:\n", sym));
    o.push_str("\tmovq %rbp, %rsp\n");
    o.push_str("\tpopq %rbp\n");
    o.push_str("\tret\n");
    o.push_str(&format!("\t.size {}, .-{}\n", sym, sym));
}

fn slot(slot: usize) -> i64 {
    -8 * (slot as i64 + 1)
}

fn emit_inst(o: &mut String, inst: &Inst, idx: usize, f: &Function) {
    use Inst::*;
    match inst {
        PushInt(v) => {
            o.push_str(&format!("\tmovabsq ${}, %rax\n", v));
            o.push_str("\tpushq %rax\n");
        }
        PushDec(bits) => {
            o.push_str(&format!("\tmovabsq $0x{:016x}, %rax\n", bits));
            o.push_str("\tpushq %rax\n");
        }
        PushStr(s) => {
            let id = record_data(s.as_bytes().to_vec());
            o.push_str(&format!("\tleaq Lstr{}(%rip), %rax\n", id));
            o.push_str("\tpushq %rax\n");
        }
        PushBytes(b) => {
            let id = record_data(b.clone());
            o.push_str(&format!("\tleaq Lstr{}(%rip), %rax\n", id));
            o.push_str("\tpushq %rax\n");
        }
        PushBool(b) => {
            if *b {
                o.push_str("\tmovl $1, %eax\n");
            } else {
                o.push_str("\txorl %eax, %eax\n");
            }
            o.push_str("\tpushq %rax\n");
        }
        PushLocal(sl) => {
            o.push_str(&format!("\tmovq {}(%rbp), %rax\n", slot(*sl)));
            o.push_str("\tpushq %rax\n");
        }
        Store(sl) => {
            o.push_str("\tpopq %rax\n");
            o.push_str(&format!("\tmovq %rax, {}(%rbp)\n", slot(*sl)));
        }
        Pop => o.push_str("\taddq $8, %rsp\n"),
        Add | Sub | Mul | Div | Mod | Eq | Ne | Lt | Le | Gt | Ge | And | Or => {
            o.push_str("\tpopq %rcx\n");
            o.push_str("\tpopq %rax\n");
            match inst {
                Add => o.push_str("\taddq %rcx, %rax\n"),
                Sub => o.push_str("\tsubq %rcx, %rax\n"),
                Mul => o.push_str("\timulq %rcx, %rax\n"),
                Div => { o.push_str("\tcqto\n"); o.push_str("\tidivq %rcx\n"); }
                Mod => { o.push_str("\tcqto\n"); o.push_str("\tidivq %rcx\n"); o.push_str("\tmovq %rdx, %rax\n"); }
                Eq => { o.push_str("\tcmpq %rcx, %rax\n"); o.push_str("\tsete %al\n"); o.push_str("\tmovzbl %al, %eax\n"); }
                Ne => { o.push_str("\tcmpq %rcx, %rax\n"); o.push_str("\tsetne %al\n"); o.push_str("\tmovzbl %al, %eax\n"); }
                Lt => { o.push_str("\tcmpq %rcx, %rax\n"); o.push_str("\tsetl %al\n"); o.push_str("\tmovzbl %al, %eax\n"); }
                Le => { o.push_str("\tcmpq %rcx, %rax\n"); o.push_str("\tsetle %al\n"); o.push_str("\tmovzbl %al, %eax\n"); }
                Gt => { o.push_str("\tcmpq %rcx, %rax\n"); o.push_str("\tsetg %al\n"); o.push_str("\tmovzbl %al, %eax\n"); }
                Ge => { o.push_str("\tcmpq %rcx, %rax\n"); o.push_str("\tsetge %al\n"); o.push_str("\tmovzbl %al, %eax\n"); }
                And => o.push_str("\tandq %rcx, %rax\n"),
                Or => o.push_str("\torq %rcx, %rax\n"),
                _ => {}
            }
            o.push_str("\tpushq %rax\n");
        }
        Neg => {
            o.push_str("\tpopq %rax\n");
            o.push_str("\tnegq %rax\n");
            o.push_str("\tpushq %rax\n");
        }
        Not => {
            o.push_str("\tpopq %rax\n");
            o.push_str("\txorb $1, %al\n");
            o.push_str("\tmovzbl %al, %eax\n");
            o.push_str("\tpushq %rax\n");
        }
        ConcatText => {
            o.push_str("\tpopq %rsi\n");
            o.push_str("\tpopq %rdi\n");
            o.push_str("\tcall hexa_concat_text\n");
            o.push_str("\tpushq %rax\n");
        }
        Jmp(t) => o.push_str(&format!("\tjmp L{}_{}\n", fn_symbol(&f.name), t)),
        Jz(t) => {
            o.push_str("\tpopq %rax\n");
            o.push_str("\ttestq %rax, %rax\n");
            o.push_str(&format!("\tjz L{}_{}\n", fn_symbol(&f.name), t));
        }
        Call(name, argc) => {
            // args already pushed; result returned in rax. The caller owns
            // the argument stack slots: discard them BEFORE pushing the
            // result, otherwise the result gets popped away and stale
            // argument slots leak into the next stack-machine pop.
            o.push_str(&format!("\tcall {}\n", fn_symbol(name)));
            if *argc > 0 {
                o.push_str(&format!("\taddq ${}, %rsp\n", 8 * argc));
            }
            o.push_str("\tpushq %rax\n");
        }
        Return => {
            o.push_str("\tpopq %rax\n");
            o.push_str(&format!("\tjmp Lret_{}\n", fn_symbol(&f.name)));
        }
        PrintInt => {
            o.push_str("\tpopq %rdi\n");
            o.push_str("\tcall hexa_print_int\n");
        }
        PrintDec => {
            o.push_str("\tpopq %rdi\n");
            o.push_str("\tcall hexa_print_dec\n");
        }
        PrintBool => {
            o.push_str("\tpopq %rdi\n");
            o.push_str("\tcall hexa_print_bool\n");
        }
        PrintText | PrintBytes => {
            o.push_str("\tpopq %rdi\n");
            o.push_str("\tcall hexa_print_str\n");
        }
    }
    let _ = (idx, f);
}

/// Convenience: emit and reset data state so emission is reentrant.
pub fn emit_module(module: &Module, debug: bool) -> String {
    reset_data();
    let s = emit(module, debug);
    reset_data();
    s
}
