[package]
name = "hexa-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zeroize = "1"
getrandom = "0.2"
aes-gcm = "0.10"
chacha20poly1305 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
blake2 = "0.10"
blake3 = "1"
argon2 = "0.5"
scrypt = "0.11"
pbkdf2 = "0.12"
hkdf = "0.12"
hmac = "0.12"
ed25519-dalek = "1"
x25519-dalek = "1"
